package problems;

import api.Maths;

public class Problem2 {

	/*
	 * Each new term in the Fibonacci sequence is generated by adding the
	 * previous two terms. By starting with 1 and 2, the first 10 terms will be:
	 * 
	 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	 * 
	 * By considering the terms in the Fibonacci sequence whose values do not
	 * exceed four million, find the sum of the even-valued terms.
	 */
	
	public static void main(String[] args) {

		int total = 0;

		for (int i = 1; i < 33; i++) {
			if (Maths.isEven(Maths.fibonacciNumber(i))
					&& Maths.fibonacciNumber(i) < 4000000)
				total += Maths.fibonacciNumber(i);
		}

		System.out.println(total);
	}
}
